### ISSUE TITLE
define observables

### ISSUE THREAD

**Issue by mopichalova** [sybila/eBCSgen#108]
define observables - pools, scaling (basic arithmetics).

**Comment by mopichalova** [comment]
What are pools and scaling in the context of observables? And how should the basic arithmetics be incorporated in the observables?

**Comment by xtrojak** [comment]
So I think the basic usage of observables is something like this:

```
obs_A_all: A{i}::cell + A{a}::cell
```

`obs_A_all` is now a pool `A`s in multiple states. We also used some arithmetics there as you can see.

Scaling is just arithmetics with a constant, so you also want to allow constants. For example:

```
scaled_A: 1000 * A{i}::cell
```

**Comment by mopichalova** [comment]
Thank you!
