### ISSUE TITLE
Syntactic grammar improvements

### ISSUE THREAD

**Issue by mopichalova** [sybila/eBCSgen#93]
- [ ] order of individual sections (rules, inits, etc) should be arbitrary
- [ ] require all parts to be separated by newlines - for example, rules can all be specified inline, which is not desired behaviour and can cause weird syntactic constructs

**Comment by xtrojak** [comment]
In addition to requiring newlines in particular positions, it would be nice to achieve also the opposite - currently, it's possible to write newline in the middle of writing a structure agent (as an example). However, I was unable to find how to avoid this in `lark`.

**Comment by xtrojak** [comment]
Fixed in #94.
